### ISSUE TITLE
build fails with pre-1.0 APR because of call of apr_socket_create with 5 arguments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [krime/serf#81]
```
What steps will reproduce the problem?
try to build with version of APR < 1.0

excerpt from configure:

configure: Apache Portable Runtime (APR) library configuration
checking for APR... yes
checking APR version... 0.9.17
configure: Apache Portable Runtime Utility (APRUTIL) library configuration
checking for APR-util... yes
checking APR-UTIL version... 0.9.15

build stops with:

incoming.c: In function 'serf_listener_create':
incoming.c:144: warning: passing argument 4 of 'apr_socket_create' makes pointer
 from integer without a cast
incoming.c:144: error: too many arguments to function 'apr_socket_create'


What version of the product are you using? On what operating system?
serf 0.7.2 on Linux 


Please provide any additional information below.
The problem is still present in trunk. The call of
apr_socket_create must pass different arguments depending on
APR_MAJOR_VERSION (see the call of apr_socket_create in outgoing.c)


Cheers, Roderich



```

Original issue reported on code.google.com by `roderich...@gmail.com` on 8 Jul 2011 at 8:43
